### PR TITLE
TYNSTEP-1364 Updated logic for getting verse number to handle interlinear verses

### PR DESCRIPTION
**Pull request by thetallweeks**

### CODE REVIEW

**Comment by DavidIB** [comment]
My system is not happy.
[messages.txt](https://github.com/tyndale/step/files/2054834/messages.txt)
afteruupdate
However, I'm new to testing things this way, so I might be doing something stupid. Can you see anything in my terminal and messages?

**Comment by thetallweeks** [comment]
I'm currently seeing issues with http://crosswire.org/mvn/content/groups/public/ being inaccessible. I wonder if this is causing you problems as well

**Comment by chrisburrell** [comment]
@DavidIB David, I think you need to do a clean build (mvn clean install) as Intellij seems to have lost its classes.

@thetallweeks looks good and I'll let David merge when he's seeing it - but (having not tested), looks very reasonable change.

**Comment by DavidIB** [comment]
That doesn't look good - Crosswire are usually on top of things. 
But I don't think that would cause us problems. We are using  a branch of their code which I think is a fair way off the tracks now, isn't it @chrisburrell ?

**Comment by DavidIB** [comment]
@chrisburrell I merged this and TYNSTEP-1361 then and restarted dev.STEPBible.org, but I'm not seeing either change. That is, links are still in a different font colour - see eg
http://dev.stepbible.org/?q=reference=Gen.1|version=NETfull&options=NHVUG
and Psa.20.8 still shows a blank QuickLexicon if you hover over the last Heb word - see:
http://dev.stepbible.org/?q=version=ESV|version=OHB|reference=Ps.20.8&options=UVGVNH&display=INTERLEAVED
Is there something else I should have done?

**Comment by thetallweeks** [comment]
Yeah my issue earlier was that I synced with the wrong branch of jsword (master instead of jsword-tyndale-master) so ignore my comment about crosswire.

I would think PR merges would need to trigger a build/redeploy to dev.stepbible in order for the changes to be visible. Maybe that is not halyting/set up

**Comment by chrisburrell** [comment]
Hi @DavidIB 

The build is broken - it was broken on build #925: http://build.stepbible.org/job/STEP/925/console

Looks like Patrick failed the build: https://github.com/tyndale/step/commit/729246c2972b79e4a14c616fbdddacadbe067fc1 according to Jenkins

or at least that's the first time it broke. 

Looks like maven is out of date, so let me update it:

[ERROR] Failed to execute goal nl.geodienstencentrum.maven:sass-maven-plugin:3.5.3:update-stylesheets (scss-compile) on project step-web: The plugin nl.geodienstencentrum.maven:sass-maven-plugin:3.5.3 requires Maven version 3.2.5 -> [Help 1]

**Comment by chrisburrell** [comment]
Jenkins maven has been updated but now need to update the maven plugins for it - so will update later. @thetallweeks i've created a login for you so you can see what's happening.

**Comment by chrisburrell** [comment]
@DavidIB @thetallweeks there should be no need to restart the dev server - all that happens as part of the core build (Step). But we do need to keep the build stable (unfortunate event here). Also, it looks like the email isn't working quite right - some authentication issue

**Comment by chrisburrell** [comment]
As far as I can tell, build is now fixed and fix has worked - well done @thetallweeks Good to have you on board :)

**Comment by DavidIB** [comment]
I’m still failing to build STEPBible, like last week. 

I’m getting Build Fail with our fork of JSword, so I’m using skipTests (I don’t think this is unusual) 

But with STEP I’m getting build failure with lots of Class errors – see attached. 

 

Just to be sure, this is straight after VCS>Update project, with Git set to “master”

 

Are you getting this, or is your build OK?

Do you think a fresh clone would help?

 

David IB

**Pull request merged**
